# Generated by Django 5.0.1 on 2024-01-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_commentsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsmodel',
            name='post_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
